// GENERATED by scripts/sync-example-aliases.mjs — do not edit by hand.
// Complete public subpath set for source-mode integration. Source of truth:
// packages/angular/publishable-projects.json. Refresh with `pnpm sync:aliases`.
// Statically imported by consumer-boundary.spec.ts so a missing or stale
// alias fails the example build/test compile instead of hiding at runtime.
import * as accordion from '@egose/shadcn-theme-ng/accordion';
import * as alert from '@egose/shadcn-theme-ng/alert';
import * as alertDialog from '@egose/shadcn-theme-ng/alert-dialog';
import * as aspectRatio from '@egose/shadcn-theme-ng/aspect-ratio';
import * as autocomplete from '@egose/shadcn-theme-ng/autocomplete';
import * as avatar from '@egose/shadcn-theme-ng/avatar';
import * as badge from '@egose/shadcn-theme-ng/badge';
import * as basicAlert from '@egose/shadcn-theme-ng/basic-alert';
import * as breadcrumb from '@egose/shadcn-theme-ng/breadcrumb';
import * as button from '@egose/shadcn-theme-ng/button';
import * as buttonGroup from '@egose/shadcn-theme-ng/button-group';
import * as calendar from '@egose/shadcn-theme-ng/calendar';
import * as card from '@egose/shadcn-theme-ng/card';
import * as carousel from '@egose/shadcn-theme-ng/carousel';
import * as checkbox from '@egose/shadcn-theme-ng/checkbox';
import * as collapsible from '@egose/shadcn-theme-ng/collapsible';
import * as combobox from '@egose/shadcn-theme-ng/combobox';
import * as command from '@egose/shadcn-theme-ng/command';
import * as confirmationDialog from '@egose/shadcn-theme-ng/confirmation-dialog';
import * as contextMenu from '@egose/shadcn-theme-ng/context-menu';
import * as datePicker from '@egose/shadcn-theme-ng/date-picker';
import * as dialog from '@egose/shadcn-theme-ng/dialog';
import * as drawer from '@egose/shadcn-theme-ng/drawer';
import * as dropdownMenu from '@egose/shadcn-theme-ng/dropdown-menu';
import * as empty from '@egose/shadcn-theme-ng/empty';
import * as field from '@egose/shadcn-theme-ng/field';
import * as formCheckbox from '@egose/shadcn-theme-ng/form-checkbox';
import * as formDatePicker from '@egose/shadcn-theme-ng/form-date-picker';
import * as formField from '@egose/shadcn-theme-ng/form-field';
import * as formFieldSimple from '@egose/shadcn-theme-ng/form-field-simple';
import * as formSearchableMultiselect from '@egose/shadcn-theme-ng/form-searchable-multiselect';
import * as formSelect from '@egose/shadcn-theme-ng/form-select';
import * as formTextInput from '@egose/shadcn-theme-ng/form-text-input';
import * as formTextarea from '@egose/shadcn-theme-ng/form-textarea';
import * as hoverCard from '@egose/shadcn-theme-ng/hover-card';
import * as icon from '@egose/shadcn-theme-ng/icon';
import * as input from '@egose/shadcn-theme-ng/input';
import * as inputGroup from '@egose/shadcn-theme-ng/input-group';
import * as inputOtp from '@egose/shadcn-theme-ng/input-otp';
import * as item from '@egose/shadcn-theme-ng/item';
import * as kbd from '@egose/shadcn-theme-ng/kbd';
import * as label from '@egose/shadcn-theme-ng/label';
import * as layoutSimple from '@egose/shadcn-theme-ng/layout-simple';
import * as menu from '@egose/shadcn-theme-ng/menu';
import * as menubar from '@egose/shadcn-theme-ng/menubar';
import * as nativeSelect from '@egose/shadcn-theme-ng/native-select';
import * as navigationMenu from '@egose/shadcn-theme-ng/navigation-menu';
import * as pagination from '@egose/shadcn-theme-ng/pagination';
import * as popover from '@egose/shadcn-theme-ng/popover';
import * as progress from '@egose/shadcn-theme-ng/progress';
import * as radioGroup from '@egose/shadcn-theme-ng/radio-group';
import * as resizable from '@egose/shadcn-theme-ng/resizable';
import * as scrollArea from '@egose/shadcn-theme-ng/scroll-area';
import * as searchableMultiselect from '@egose/shadcn-theme-ng/searchable-multiselect';
import * as select from '@egose/shadcn-theme-ng/select';
import * as separator from '@egose/shadcn-theme-ng/separator';
import * as sheet from '@egose/shadcn-theme-ng/sheet';
import * as sidebar from '@egose/shadcn-theme-ng/sidebar';
import * as skeleton from '@egose/shadcn-theme-ng/skeleton';
import * as slider from '@egose/shadcn-theme-ng/slider';
import * as sonner from '@egose/shadcn-theme-ng/sonner';
import * as spinner from '@egose/shadcn-theme-ng/spinner';
import * as switchLib from '@egose/shadcn-theme-ng/switch';
import * as table from '@egose/shadcn-theme-ng/table';
import * as tabs from '@egose/shadcn-theme-ng/tabs';
import * as textarea from '@egose/shadcn-theme-ng/textarea';
import * as toggle from '@egose/shadcn-theme-ng/toggle';
import * as toggleGroup from '@egose/shadcn-theme-ng/toggle-group';
import * as tooltip from '@egose/shadcn-theme-ng/tooltip';
import * as typography from '@egose/shadcn-theme-ng/typography';
import * as utils from '@egose/shadcn-theme-ng/utils';

export const EXAMPLE_PUBLIC_SUBPATHS = [
  'accordion',
  'alert',
  'alert-dialog',
  'aspect-ratio',
  'autocomplete',
  'avatar',
  'badge',
  'basic-alert',
  'breadcrumb',
  'button',
  'button-group',
  'calendar',
  'card',
  'carousel',
  'checkbox',
  'collapsible',
  'combobox',
  'command',
  'confirmation-dialog',
  'context-menu',
  'date-picker',
  'dialog',
  'drawer',
  'dropdown-menu',
  'empty',
  'field',
  'form-checkbox',
  'form-date-picker',
  'form-field',
  'form-field-simple',
  'form-searchable-multiselect',
  'form-select',
  'form-text-input',
  'form-textarea',
  'hover-card',
  'icon',
  'input',
  'input-group',
  'input-otp',
  'item',
  'kbd',
  'label',
  'layout-simple',
  'menu',
  'menubar',
  'native-select',
  'navigation-menu',
  'pagination',
  'popover',
  'progress',
  'radio-group',
  'resizable',
  'scroll-area',
  'searchable-multiselect',
  'select',
  'separator',
  'sheet',
  'sidebar',
  'skeleton',
  'slider',
  'sonner',
  'spinner',
  'switch',
  'table',
  'tabs',
  'textarea',
  'toggle',
  'toggle-group',
  'tooltip',
  'typography',
  'utils',
] as const;

export type ExamplePublicSubpath = (typeof EXAMPLE_PUBLIC_SUBPATHS)[number];

export const EXAMPLE_PUBLIC_MODULES: Record<ExamplePublicSubpath, Record<string, unknown>> = {
  accordion: accordion as unknown as Record<string, unknown>,
  alert: alert as unknown as Record<string, unknown>,
  'alert-dialog': alertDialog as unknown as Record<string, unknown>,
  'aspect-ratio': aspectRatio as unknown as Record<string, unknown>,
  autocomplete: autocomplete as unknown as Record<string, unknown>,
  avatar: avatar as unknown as Record<string, unknown>,
  badge: badge as unknown as Record<string, unknown>,
  'basic-alert': basicAlert as unknown as Record<string, unknown>,
  breadcrumb: breadcrumb as unknown as Record<string, unknown>,
  button: button as unknown as Record<string, unknown>,
  'button-group': buttonGroup as unknown as Record<string, unknown>,
  calendar: calendar as unknown as Record<string, unknown>,
  card: card as unknown as Record<string, unknown>,
  carousel: carousel as unknown as Record<string, unknown>,
  checkbox: checkbox as unknown as Record<string, unknown>,
  collapsible: collapsible as unknown as Record<string, unknown>,
  combobox: combobox as unknown as Record<string, unknown>,
  command: command as unknown as Record<string, unknown>,
  'confirmation-dialog': confirmationDialog as unknown as Record<string, unknown>,
  'context-menu': contextMenu as unknown as Record<string, unknown>,
  'date-picker': datePicker as unknown as Record<string, unknown>,
  dialog: dialog as unknown as Record<string, unknown>,
  drawer: drawer as unknown as Record<string, unknown>,
  'dropdown-menu': dropdownMenu as unknown as Record<string, unknown>,
  empty: empty as unknown as Record<string, unknown>,
  field: field as unknown as Record<string, unknown>,
  'form-checkbox': formCheckbox as unknown as Record<string, unknown>,
  'form-date-picker': formDatePicker as unknown as Record<string, unknown>,
  'form-field': formField as unknown as Record<string, unknown>,
  'form-field-simple': formFieldSimple as unknown as Record<string, unknown>,
  'form-searchable-multiselect': formSearchableMultiselect as unknown as Record<string, unknown>,
  'form-select': formSelect as unknown as Record<string, unknown>,
  'form-text-input': formTextInput as unknown as Record<string, unknown>,
  'form-textarea': formTextarea as unknown as Record<string, unknown>,
  'hover-card': hoverCard as unknown as Record<string, unknown>,
  icon: icon as unknown as Record<string, unknown>,
  input: input as unknown as Record<string, unknown>,
  'input-group': inputGroup as unknown as Record<string, unknown>,
  'input-otp': inputOtp as unknown as Record<string, unknown>,
  item: item as unknown as Record<string, unknown>,
  kbd: kbd as unknown as Record<string, unknown>,
  label: label as unknown as Record<string, unknown>,
  'layout-simple': layoutSimple as unknown as Record<string, unknown>,
  menu: menu as unknown as Record<string, unknown>,
  menubar: menubar as unknown as Record<string, unknown>,
  'native-select': nativeSelect as unknown as Record<string, unknown>,
  'navigation-menu': navigationMenu as unknown as Record<string, unknown>,
  pagination: pagination as unknown as Record<string, unknown>,
  popover: popover as unknown as Record<string, unknown>,
  progress: progress as unknown as Record<string, unknown>,
  'radio-group': radioGroup as unknown as Record<string, unknown>,
  resizable: resizable as unknown as Record<string, unknown>,
  'scroll-area': scrollArea as unknown as Record<string, unknown>,
  'searchable-multiselect': searchableMultiselect as unknown as Record<string, unknown>,
  select: select as unknown as Record<string, unknown>,
  separator: separator as unknown as Record<string, unknown>,
  sheet: sheet as unknown as Record<string, unknown>,
  sidebar: sidebar as unknown as Record<string, unknown>,
  skeleton: skeleton as unknown as Record<string, unknown>,
  slider: slider as unknown as Record<string, unknown>,
  sonner: sonner as unknown as Record<string, unknown>,
  spinner: spinner as unknown as Record<string, unknown>,
  switch: switchLib as unknown as Record<string, unknown>,
  table: table as unknown as Record<string, unknown>,
  tabs: tabs as unknown as Record<string, unknown>,
  textarea: textarea as unknown as Record<string, unknown>,
  toggle: toggle as unknown as Record<string, unknown>,
  'toggle-group': toggleGroup as unknown as Record<string, unknown>,
  tooltip: tooltip as unknown as Record<string, unknown>,
  typography: typography as unknown as Record<string, unknown>,
  utils: utils as unknown as Record<string, unknown>,
};
