name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@640a1c2554105b57832a23eea0b4672fc7a790d5
    with:
      # pnpm store path
      path: |
        ~/.local/share/pnpm/store/v3
      key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      restore-keys: |
        ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-

  - name: Install Root NPM packages
    run: |
      pnpm install --no-frozen-lockfile
    shell: bash

  - name: Install Package NPM packages
    run: pnpm install --no-frozen-lockfile
    shell: bash
    working-directory: package

  - name: Install Nextjs app NPM packages
    run: pnpm install --no-frozen-lockfile
    shell: bash
    working-directory: apps/nextjs

  - name: Install Angular app NPM packages
    run: pnpm install --no-frozen-lockfile
    shell: bash
    working-directory: apps/angular
