name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
    with:
      # pnpm store path
      path: |
        ~/.local/share/pnpm/store/v3
      key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      restore-keys: |
        ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-

  - name: Install Root NPM packages
    run: |
      pnpm install --no-frozen-lockfile
    shell: bash

  - name: Install Package React NPM packages
    run: pnpm install --no-frozen-lockfile
    shell: bash
    working-directory: packages/react

  - name: Install Package Angular NPM packages
    run: pnpm install --no-frozen-lockfile
    shell: bash
    working-directory: packages/angular

  - name: Install Nextjs app NPM packages
    run: pnpm install --no-frozen-lockfile
    shell: bash
    working-directory: packages/react/@examples/nextjs

  - name: Install Angular app NPM packages
    run: pnpm install --no-frozen-lockfile
    shell: bash
    working-directory: packages/angular/@examples/standard
