name: Publish Nextjs in GitHub Pages

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm
      with:
        context: react

    - name: Nextjs Build 📦
      run: |
        pnpm build
        touch out/.nojekyll
      working-directory: packages/react/@examples/nextjs

    - name: Nextjs Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445
      with:
        folder: packages/react/@examples/nextjs/out
        branch: pages-nextjs
        clean: true
        force: true
