name: Run pre-commit Hooks

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Lint Current Commits
      run: npx commitlint --last --verbose

    - name: Run Pre-commit Hooks on CI
      run: |
        chmod +x .bin/prettier.sh .bin/commitlint.sh

    - name: Run pre-commit
      uses: egose/actions/precommit@05add1b5a7a995374c1bb375f3e920203efcc313
      with:
        config: .pre-commit-config.yaml
        commit-on-push: true
        commit-on-pr: false
