name: Run pre-commit Hooks

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm
      with:
        context: root

    - name: Lint Current Commits
      run: npx commitlint --last --verbose

    - name: Run pre-commit
      uses: egose/actions/precommit@0802d5eb78229994c066ea07b8c576dd38adfb5b
      with:
        config: .pre-commit-config.yaml
        commit-on-push: true
        commit-on-pr: false
